### ISSUE TITLE
Issue while joining two hive tables stored on ES

### ISSUE THREAD

**Issue by mungeol** [elasticsearch/elasticsearch-hadoop#293]
Hi,

I got an exception/error while joining two hive tables stored on ES.
the tables I used are like below

CREATE EXTERNAL TABLE member
(
mem_idx bigint,
id string,
msaram_nm string,
dept_nm string
)
STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler'
TBLPROPERTIES
(
'es.resource' = 'jdbc/member'
);

CREATE EXTERNAL TABLE test
(
mem_idx bigint
)
STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler'
TBLPROPERTIES
(
'es.resource' = 'test/test'
);

example data of the member table
1830252 foo bar test

example data of the test table
1830252

and I use 'select \* from test join member on test.mem_idx = member.mem_idx' to join these tables.
but I got the exception/error like below

Exception in thread "main" org.apache.hive.com.esotericsoftware.kryo.KryoException: Unable to find class: org.elasticsearch.hadoop.hive.EsHiveInputFormat
Serialization trace:
inputFileFormatClass (org.apache.hadoop.hive.ql.plan.TableDesc)
tblDesc (org.apache.hadoop.hive.ql.plan.FetchWork)
aliasToFetchWork (org.apache.hadoop.hive.ql.plan.MapredLocalWork)
        at org.apache.hive.com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:138)
        at org.apache.hive.com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:115)
        at org.apache.hive.com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:656)
        at org.apache.hive.com.esotericsoftware.kryo.serializers.DefaultSerializers$ClassSerializer.read(DefaultSerializers.java:238)
        at org.apache.hive.com.esotericsoftware.kryo.serializers.DefaultSerializers$ClassSerializer.read(DefaultSerializers.java:226)
        at org.apache.hive.com.esotericsoftware.kryo.Kryo.readObjectOrNull(Kryo.java:745)
        at org.apache.hive.com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:113)
        at org.apache.hive.com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:507)
        at org.apache.hive.com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:694)
        at org.apache.hive.com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:106)
        at org.apache.hive.com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:507)
        at org.apache.hive.com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:776)
        at org.apache.hive.com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:139)
        at org.apache.hive.com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:17)
        at org.apache.hive.com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:694)
        at org.apache.hive.com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:106)
        at org.apache.hive.com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:507)
        at org.apache.hive.com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:672)
        at org.apache.hadoop.hive.ql.exec.Utilities.deserializeObjectByKryo(Utilities.java:829)
        at org.apache.hadoop.hive.ql.exec.Utilities.deserializePlan(Utilities.java:739)
        at org.apache.hadoop.hive.ql.exec.Utilities.deserializePlan(Utilities.java:752)
        at org.apache.hadoop.hive.ql.exec.mr.ExecDriver.main(ExecDriver.java:726)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:212)
Caused by: java.lang.ClassNotFoundException: org.elasticsearch.hadoop.hive.EsHiveInputFormat
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:270)
        at org.apache.hive.com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:136)
        ... 26 more
Execution failed with exit status: 1
Obtaining error information

Task failed!
Task ID:
  Stage-4

Logs:

/tmp/mungeol/hive.log
FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.mr.MapredLocalTask

what I am doing now is extracting these two tables' data to two new hive table and performing the 'join' task. It is working, but inefficient.
Is there any solution for this problem?

Thanks.

-----
environmental information
centos base 6.4 64-bit / java version "1.7.0_55"
CDH-5.1.2-1.cdh5.1.2.p0.3
hive 0.12.0
elasticsearch-hadoop-2.0.1
3 nodes' hadoop and es cluster

**Comment by costin** [comment]
Closing the issue.

**Comment by Jayusman123** [comment]
How to insert data hive in elasticsearch if i finish create table with STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler'..? Because i found error...

**Comment by costin** [comment]
@Jayusman123 Please stop hijacking existing bug reports - if you have questions, use the mailing list instead (which I've already pointed out on the other bug request that you have raised). Cross-posting will not help you get answers, quite the opposite. Thank you.
